# Generated by Django 3.2.4 on 2021-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('numIdenti', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Identificación')),
                ('photo', models.ImageField(upload_to='', verbose_name='Fotografía')),
                ('nombreProveedor', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('numContactoProveedor', models.IntegerField(verbose_name='Número de Contacto (+569)')),
                ('direccionProveedor', models.CharField(max_length=150, verbose_name='Dirección')),
                ('correoProveedor', models.CharField(max_length=100, verbose_name='Correo Electrónico')),
                ('paisProveedor', models.CharField(max_length=50, verbose_name='País')),
                ('contraseña', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('monedaPago', models.CharField(max_length=5, verbose_name='Moneda de Pago')),
            ],
        ),
    ]
